/**
 * Section ids in document order.
 *
 * `NAV_KEYS` is what the navbar and the drawer list. `SECTION_IDS` adds the
 * hero, which has no nav link but is still a scroll position the language
 * toggle has to be able to name.
 *
 * These live here rather than in `Navbar` because `LanguageToggle` needs them
 * and `Navbar` renders `LanguageToggle` — importing them from there would be a
 * cycle. Not in `utils/constants.ts` either: that file is regenerated by
 * `scripts/gen-build-meta.mjs`, which deletes any export it did not write.
 */
export const NAV_KEYS = [
    'about',
    'experience',
    'skills',
    'projects',
    'education',
    'contact',
] as const;

export const SECTION_IDS = ['hero', ...NAV_KEYS] as const;
